import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main1 from '../components/Main1';
import Main2 from '../components/Main2';
import Main3 from '../components/Main3';
import Main4 from '../components/Main4';
import Main5 from '../components/Main5';
import Cards from '../components/Cards';
import Footer from '../components/Footer';



export default function Home() {
  return (
    <div >
      <Navbar></Navbar>
      <Main1></Main1>
      <Main2></Main2>
      <Main3></Main3>
      <Main4></Main4>
      <Main5></Main5>
      <Cards></Cards>
      <Footer></Footer>
      <Head>
        <title>Event Ui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
    </div>
  )
}
